# Config for train and eval.

# model
'name' : 'MobileNet025'
'device_target': "GPU"
'variance': [0.1, 0.2]
'clip': False
'loc_weight': 2.0
'class_weight': 1.0
'landm_weight': 1.0
'batch_size': 16
'num_workers': 1
'num_anchor': 16800
'ngpu': 1
'image_size': 640
'in_channel': 32
'out_channel': 64
'match_thresh': 0.35
'num_classes' : 2
"mode" : 'Graph'
'grad_clip': False

# opt
'optim': 'sgd'
'momentum': 0.9
'weight_decay': 0.0005

# seed
'seed': 1

# lr
'epoch': 120
'decay1': 70
'decay2': 90
'lr_type': 'dynamic_lr'
'initial_lr': 0.02
'warmup_epoch': 5
'gamma': 0.1

# checkpoint
'ckpt_path': './ckpt/'
'save_checkpoint_steps': 402
'keep_checkpoint_max': 10
'resume_net': ~


# dataset
'training_dataset': '/home/d1/czp21/czp/mindspore/retinaface/retinaface_mindinsight/data/WiderFace/train/label.txt'
'pretrain': False
'pretrain_path': ~

# val
'val_model': '/home/d1/czp21/czp/mindspore/20221011/mindface/mobilenet/RetinaFace-119_59_bs16lr02.ckpt'
'val_dataset_folder': '/home/d1/czp21/czp/mindspore/retinaface/retinaface_mindinsight/data/WiderFace/val/'
'val_origin_size': True
'val_confidence_threshold': 0.02
'val_nms_threshold': 0.4
'val_iou_threshold': 0.5
'val_save_result': False
'val_predict_save_folder': './widerface_result'
'val_gt_dir': '/home/d1/czp21/czp/mindspore/retinaface/retinaface_mindinsight/data/WiderFace/ground_truth'

